export const CREATE_USER = `
INSERT INTO USERS(USER_NAME, USER_EMAIL, USER_PASSWORD, USER_MOBILE_NUMBER, USER_ROLE) VALUES ($1, $2, $3, $4, $5)
`;

export const GET_USER_BY_EMAIL = `
    SELECT USER_ID, USER_PASSWORD, USER_ROLE FROM USERS WHERE USER_EMAIL = $1
`;
