export const CREATE_USER = `
INSERT INTO USERS(USER_NAME, USER_FULL_NAME, USER_EMAIL, USER_PASSWORD, USER_MOBILE_NUMBER, USER_ROLE) VALUES ($1, $2, $3, $4, $5, $6)
`;

export const GET_USER_BY_EMAIL = `
    SELECT USER_ID, USER_NAME, USER_PASSWORD, USER_ROLE FROM USERS WHERE USER_EMAIL = $1
`;

export const GET_USER_BY_USERNAME = `
    SELECT USER_ID, USER_NAME, USER_FULL_NAME, USER_PASSWORD, USER_ROLE FROM USERS WHERE USER_NAME = $1
`;

export const GET_USER_BY_USER_ID = `
    SELECT USER_ID, USER_NAME, USER_FULL_NAME, USER_PASSWORD, USER_ROLE FROM USERS WHERE USER_ID = $1
`;
