version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: theatre
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"

  server:
    depends_on:
      - db
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: theatre
      PGPASSWORD: postgres
      PGPORT: 5432
