version: '3.7'

services:
  db:
    container_name: theatre-db
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: theatre
    volumes:
      - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - 'db-data:/var/lib/postgresql/data/'

  server:
    container_name: theatre-server
    depends_on:
      - db
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: theatre
      PGPASSWORD: postgres
      PGPORT: 5432

volumes:
  db-data:
