version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: theatre
    volumes:
      - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - '.db/data:/var/lib/postgresql/data/'

  server:
    depends_on:
      - db
    image: node:latest
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - ./backend/:/app
    command: bash -c "npm install && npm run dev"
    environment:
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: theatre
      PGPASSWORD: postgres
      PGPORT: 5432

  admin:
    depends_on:
      - db
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
