export const GET_ALL_SHOWS = `
    SELECT MOVIE_NAME, MOVIE_TICKET_PRICE, MOVIE_ID FROM MOVIES 
    INNER JOIN SHOWS 
    ON SHOW_MOVIE_ID = MOVIE_ID
    GROUP BY MOVIE_NAME, MOVIE_TICKET_PRICE, MOVIE_ID
`;

export const CREATE_SHOW = `
    INSERT INTO SHOWS (SHOW_MOVIE_ID, SHOW_HALL_ID, SHOW_TIME, SHOW_CREATED_BY, SHOW_UPDATED_BY) VALUES ($1, $2, $3, $4, $5)
`;
