export const CREATE_HALL = `
    INSERT INTO HALLS (HALL_NAME, HALL_TOTAL_COLUMNS, HALL_TOTAL_ROWS, HALL_CREATED_BY, HALL_UPDATED_BY) VALUES ($1, $2, $3, $4, $5)
`;

export const GET_ALL_HALLS = `
    SELECT HALL_ID, HALL_NAME AS NAME, HALL_TOTAL_COLUMNS AS TOTAL_COLUMNS, HALL_TOTAL_ROWS AS TOTAL_ROWS FROM HALLS
`;
