export const CREATE_HALL = `
    INSERT INTO HALLS (HALL_NAME, HALL_TOTAL_COLUMNS, HALL_TOTAL_ROWS, HALL_CREATED_BY, HALL_UPDATED_BY) VALUES ($1, $2, $3, $4, $5)
`;

export const GET_ALL_HALLS = `
    SELECT * FROM HALLS
`;
