export const CREATE_HALL = `
    INSERT INTO HALLS (HALL_NAME, HALL_TOTAL_COLUMNS, HALL_TOTAL_ROWS, HALL_CREATED_BY, HALL_UPDATED_BY) VALUES ($1, $2, $3, $4, $5)
`;

export const GET_ALL_HALLS = `
    SELECT HALL_ID, HALL_NAME AS NAME, HALL_TOTAL_COLUMNS AS TOTAL_COLUMNS, HALL_TOTAL_ROWS AS TOTAL_ROWS FROM HALLS
`;

export const UPDATE_HALL_BY_ID = `
    UPDATE HALLS 
    SET HALL_NAME = $1, 
    HALL_TOTAL_COLUMNS = $2, 
    HALL_TOTAL_ROWS = $3, 
    HALL_UPDATED_BY = $4,
    HALL_UPDATED_AT = NOW()
    WHERE HALL_ID = $5
`;
