export const GET_SHOW_AVAILABILITY = `
    SELECT BOOKING_SEQUENCE_NUMBER AS SEQUENCE_NUMBER, BOOKING_STATUS AS STATUS FROM BOOKINGS 
    WHERE BOOKING_SHOW_ID  = $1
`;

export const GET_HALL_DETAILS_BY_SHOW_ID = `
    SELECT HALL_ID, HALL_NAME, HALL_TOTAL_COLUMNS AS TOTAL_COLUMNS, HALL_TOTAL_ROWS AS TOTAL_ROWS FROM SHOWS 
    INNER JOIN HALLS 
    ON SHOW_HALL_ID = HALL_ID
    WHERE SHOW_ID = $1
`;

export const CHECK_IF_ARE_SEATS_TAKEN = `
    SELECT BOOKING_SHOW_ID, BOOKING_SEQUENCE_NUMBER, BOOKING_STATUS FROM BOOKINGS 
    WHERE BOOKING_SHOW_ID = $1
    AND BOOKING_SEQUENCE_NUMBER = ANY ($2) 
    AND BOOKING_STATUS = 'TAKEN' FOR UPDATE
`;

export const BOOK_SINGLE_TICKET = `
    INSERT INTO BOOKINGS (BOOKING_USER_ID, BOOKING_SHOW_ID, BOOKING_SEQUENCE_NUMBER, BOOKING_STATUS, BOOKING_CREATED_BY, BOOKING_UPDATED_BY) 
    VALUES ($1, $2, $3,  'TAKEN', $4, $5);
`;

export const GET_USER_BOOKINGS = `
    SELECT 
    BOOKING_SUMMARY_ID AS BOOKING_ID,
    BOOKING_SUMMARY_MOVIE_ID AS MOVIE_ID,
    BOOKING_SUMMARY_MOVIE_NAME AS MOVIE_NAME,
    BOOKING_SUMMARY_SHOW_TIME AS SHOW_TIME,
    BOOKING_SUMMARY_USER_ID AS USER_ID,
    BOOKING_SUMMARY_SHOW_ID AS SHOW_ID,
    BOOKING_SUMMARY_BOOKED_SEATS AS BOOKED_SEATS,
    BOOKING_SUMMARY_CONFIRMED AS CONFIRMED,
    BOOKING_SUMMARY_CHECKED_IN AS CHECKED_IN
    FROM BOOKING_SUMMARY
    WHERE BOOKING_SUMMARY_USER_ID = $1
`;

export const GET_CURRENT_BOOKING_SUMMARY = `
    SELECT MOVIE_ID, MOVIE_NAME, SHOW_TIME, BOOKING_USER_ID, BOOKING_SHOW_ID, STRING_AGG(BOOKING_SEQUENCE_NUMBER::VARCHAR, ', ') AS BOOKED_SEATS, true, false, $3, $4 FROM BOOKINGS
    INNER JOIN SHOWS
    ON BOOKING_SHOW_ID = SHOW_ID
    INNER JOIN MOVIES
    ON SHOW_MOVIE_ID = MOVIE_ID
    WHERE BOOKING_USER_ID = $1 AND BOOKING_SHOW_ID = $2
    GROUP BY BOOKING_SHOW_ID, BOOKING_USER_ID, MOVIE_ID, MOVIE_NAME, SHOW_TIME
`;

export const ADD_BOOKING_SUMMARY = `
    INSERT INTO BOOKING_SUMMARY (
        BOOKING_SUMMARY_MOVIE_ID,
        BOOKING_SUMMARY_MOVIE_NAME,
        BOOKING_SUMMARY_SHOW_TIME,
        BOOKING_SUMMARY_USER_ID,
        BOOKING_SUMMARY_SHOW_ID,
        BOOKING_SUMMARY_BOOKED_SEATS,
        BOOKING_SUMMARY_CONFIRMED,
        BOOKING_SUMMARY_CHECKED_IN,
        BOOKING_SUMMARY_CREATED_BY,
        BOOKING_SUMMARY_UPDATED_BY
    )
    ${GET_CURRENT_BOOKING_SUMMARY}
`;
