export const GET_SHOW_AVAILABILITY = `
    SELECT BOOKING_SEQUENCE_NUMBER, BOOKING_STATUS FROM BOOKINGS 
    WHERE BOOKING_SHOW_ID  = $1
`;

export const GET_HALL_DETAILS_BY_SHOW_ID = `
    SELECT HALL_ID, HALL_NAME, HALL_TOTAL_COLUMNS, HALL_TOTAL_ROWS FROM SHOWS 
    INNER JOIN HALLS 
    ON SHOW_HALL_ID = HALL_ID
    WHERE SHOW_ID = $1
`;

export const CHECK_IF_ARE_SEATS_TAKEN = `
    SELECT BOOKING_SHOW_ID, BOOKING_SEQUENCE_NUMBER, BOOKING_STATUS FROM BOOKINGS 
    WHERE BOOKING_SHOW_ID = $1
    AND BOOKING_SEQUENCE_NUMBER = ANY ($2) 
    AND BOOKING_STATUS = 'TAKEN' FOR UPDATE
`;

export const BOOK_SINGLE_TICKET = `
    INSERT INTO BOOKINGS (BOOKING_USER_ID, BOOKING_SHOW_ID, BOOKING_SEQUENCE_NUMBER, BOOKING_STATUS, BOOKING_CREATED_BY, BOOKING_UPDATED_BY) VALUES ($1, $2, $3,  'TAKEN', $4, $5);
`;
